### ISSUE TITLE
It is a bug here?

### ISSUE THREAD

**Issue by jerrykhh** [sheilaya/CS4386_assignment1#1]
Hello, I am not sure about that. About the requirements, the player needs to connect the three or six 'X'. But the following case, why the player 2 get a 6 score but I only get a 3 score? Therefore, I want to enquire this is incorrect or the game will skip the space to calculate the connection?

<img width="1093" alt="Screenshot 2022-02-24 at 9 11 02 PM" src="https://user-images.githubusercontent.com/47948629/155530848-c9a9434c-31a7-4aee-a920-91946782103b.png">

Thank you.

**Comment by sheilaya** [comment]
> Hello, I am not sure about that. About the requirements, the player needs to connect the three or six 'X'. But the following case, why the player 2 get a 6 score but I only get a 3 score? Therefore, I want to enquire this is incorrect or the game will skip the space to calculate the connection?
> 
> <img alt="Screenshot 2022-02-24 at 9 11 02 PM" width="1093" src="https://user-images.githubusercontent.com/47948629/155530848-c9a9434c-31a7-4aee-a920-91946782103b.png">
> 
> Thank you.

Yes, there is a bug in the alignment() function of game.py. We will fix it and thanks for finding it.

**Comment by denniskyleung** [comment]
Hi, I edited the function get_move in AIPlayer.py to let the Python computer player make random moves to try the game.

The order of moves is marked in the capture. Player 2 gets 3 points after making the 8th move {5, 1}, maybe it is the same problem?
![bug_or_mis](https://user-images.githubusercontent.com/71558511/155549078-7367dcd0-fe63-45be-9d6a-8e6a209fadec.jpg)

**Comment by sheilaya** [comment]
> Hi, I edited the function get_move in AIPlayer.py to let the Python computer player make random moves to try the game.
> 
> The order of moves is marked in the capture. Player 2 gets 3 points after making the 8th move {5, 1}, maybe it is the same problem? ![bug_or_mis](https://user-images.githubusercontent.com/71558511/155549078-7367dcd0-fe63-45be-9d6a-8e6a209fadec.jpg)

Yes, this is the same bug mentioned by jerrykhh. I just upload the modified game.py and you can test it.
